"""12.5 (0-D): 轻量数据库适配层 — SQLite / PostgreSQL 双后端.

设计原则 (docs/cogedu-整合技术方案.md 12.5 第 2 项):
  不上重型 ORM, 只做"换数据库不触碰业务逻辑"所需的最小适配:

  1. **占位符翻译**: 代码库 SQL 统一写 SQLite 风格 (:name 命名 / ? 位置),
     PostgreSQL 后端执行前翻译为 psycopg 格式 (%(name)s / %s)
  2. **行值归一化**: PG 的 BYTEA 返回 memoryview (SQLite 返回 bytes),
     未来 JSONB 列会返回 dict/list (SQLite 返回 JSON 字符串) — 统一拉平
     到 SQLite 语义, 上层代码零感知
  3. **executescript 语义**: SQLite 有 executescript, psycopg 没有 —
     代理层按分号拆分逐句执行 (本仓库 DDL 不含字符串内分号, 见约束)
  4. **事务语义**: 见 db.py Database.tx() — PG 用 autocommit 连接 +
     conn.transaction() 块, 语义对齐 SQLite 的显式 commit/rollback

约束 (translate_sql 的正确性前提, 违反会静默错译):
  - SQL 字符串字面量内不得出现 :word 或 ? (当前全部 SQL 已核查合规;
    新 SQL 引入此类字面量时必须用参数绑定, 不许内插)
  - SQL 内不得出现 :: 显式类型转换写法 (负向断言 (?<![:\\w]) 已规避误译,
    但为可读性同样禁止)
"""
from __future__ import annotations

import json
import re
from typing import Any

BACKEND_SQLITE = "sqlite"
BACKEND_POSTGRES = "postgres"

# PG DSN scheme 前缀 (db.py / 两个 store / event_log 共用同一识别逻辑)
_PG_SCHEMES = ("postgres://", "postgresql://", "postgresql+psycopg://")

# :name → %(name)s (负向断言排除 ::cast 与标识符中间的冒号, 如时间字面量)
_NAMED_PARAM_RE = re.compile(r"(?<![:\w]):([a-zA-Z_][a-zA-Z0-9_]*)")


def is_pg_dsn(value: str) -> bool:
    """判断字符串是否是 PostgreSQL DSN (而非 SQLite 文件路径)."""
    return isinstance(value, str) and value.startswith(_PG_SCHEMES)


def detect_backend(path_or_dsn: str) -> str:
    """从连接描述识别后端: DSN scheme → postgres, 否则视为 SQLite 文件路径."""
    return BACKEND_POSTGRES if is_pg_dsn(path_or_dsn) else BACKEND_SQLITE


def translate_sql(sql: str, backend: str) -> str:
    """把代码库统一的 SQLite 风格 SQL 翻译为目标后端方言.

    只翻译占位符 (SQLite :name / ? → psycopg %(name)s / %s);
    其余语法由 DDL 层保证双后端兼容 (见 pg_schema.py 注记):
      - INSERT OR IGNORE → 改写为 ON CONFLICT DO NOTHING (两后端都支持)
      - AUTOINCREMENT → GENERATED BY DEFAULT AS IDENTITY (仅 DDL 层差异)
      - lastrowid → RETURNING (两后端都支持, SQLite ≥3.35)
    """
    if backend != BACKEND_POSTGRES:
        return sql
    sql = _NAMED_PARAM_RE.sub(r"%(\1)s", sql)
    sql = sql.replace("?", "%s")
    return sql


def normalize_value(value: Any) -> Any:
    """把 PG 驱动返回值拉平到 SQLite 语义 (SQLite 值原样通过).

    - memoryview → bytes (PG BYTEA; SQLite BLOB 返回 bytes)
    - dict / list → JSON 字符串 (未来 JSONB 列; SQLite JSON 列返回字符串)
      上层消费者全部 json.loads, 归一化保证两种后端读出的形状一致
    """
    if isinstance(value, memoryview):
        return value.tobytes()
    if isinstance(value, (dict, list)):
        return json.dumps(value, ensure_ascii=False, default=str)
    return value


def split_statements(script: str) -> list[str]:
    """把 executescript 风格的多语句 SQL 按分号拆分 (pg 无 executescript).

    先剥离 `--` 行注释 (DDL 注释里可能含中文分号, 直接按 `;` 拆会截断语句,
    event_log._EVENT_LOG_DDL 踩过)。约束: DDL 的字符串字面量内不得含
    分号或 `--` (当前各 DDL 已核查合规)。
    """
    stripped = "\n".join(
        line.split("--", 1)[0] for line in script.splitlines()
    )
    return [s.strip() for s in stripped.split(";") if s.strip()]


# ─── PG 连接代理 (12.5: db.py 与各 store 共用) ───────────────────────────────


class PGCursorProxy:
    """psycopg cursor 适配 — 行值归一化到 SQLite 语义 (normalize_value)."""

    def __init__(self, real: Any) -> None:
        self._real = real

    def fetchone(self) -> Any:
        row = self._real.fetchone()
        if row is None:
            return None
        return {k: normalize_value(v) for k, v in row.items()}

    def fetchall(self) -> list[dict]:
        return [
            {k: normalize_value(v) for k, v in row.items()}
            for row in self._real.fetchall()
        ]

    def __getattr__(self, name: str) -> Any:
        return getattr(self._real, name)  # rowcount / description / ...


class PGConnectionProxy:
    """psycopg 连接适配.

    - execute 前经 translate_sql 翻译占位符 (SQLite 风格 → psycopg 格式)
    - executescript 按分号拆句逐条执行 (psycopg 无 executescript)
    - 行值经 PGCursorProxy 归一化 (BYTEA memoryview → bytes 等)
    - commit/rollback 委托 (autocommit 连接上为安全 no-op; 真正的事务
      边界由各层 tx() 的 conn.transaction() 块管理)
    - 其余属性 (transaction / closed ...) 透传
    """

    def __init__(self, real: Any) -> None:
        self._real = real

    def execute(self, sql: str, params: Any = None) -> PGCursorProxy:
        return PGCursorProxy(
            self._real.execute(translate_sql(sql, BACKEND_POSTGRES), params)
        )

    def executemany(self, sql: str, seq: Any) -> Any:
        return self._real.executemany(translate_sql(sql, BACKEND_POSTGRES), seq)

    def executescript(self, script: str) -> None:
        for stmt in split_statements(script):
            self._real.execute(stmt)

    def commit(self) -> None:
        self._real.commit()

    def rollback(self) -> None:
        self._real.rollback()

    def close(self) -> None:
        self._real.close()

    def __getattr__(self, name: str) -> Any:
        return getattr(self._real, name)


def open_connection(path_or_dsn: str, timeout_sec: float = 10.0) -> tuple[str, Any]:
    """打开 SQLite 原生连接或 PG 代理连接 (12.5: 各持久化模块共用工厂).

    Returns:
        (backend, conn) — sqlite 返回原生 sqlite3.Connection (零行为变化),
        postgres 返回 autocommit + dict 行 + 占位符翻译的 PGConnectionProxy.
    """
    backend = detect_backend(path_or_dsn)
    if backend == BACKEND_POSTGRES:
        try:
            import psycopg
            import psycopg.rows
        except ImportError as e:
            raise RuntimeError(
                "PostgreSQL 后端需要 psycopg: pip install 'psycopg[binary,pool]'"
            ) from e
        real = psycopg.connect(
            path_or_dsn, autocommit=True, row_factory=psycopg.rows.dict_row
        )
        return backend, PGConnectionProxy(real)
    import sqlite3

    conn = sqlite3.connect(
        path_or_dsn,
        timeout=timeout_sec,
        detect_types=sqlite3.PARSE_DECLTYPES,
        # 多线程访问约定 (v0.51.1 范式): check_same_thread=False + WAL
        check_same_thread=False,
    )
    conn.row_factory = sqlite3.Row
    # 注意: 这里**不**设 PRAGMA foreign_keys=ON — 历史行为是 Database 自己的
    # 连接开 FK (db.py conn property), 而 EventLog.from_sqlite 的独立连接
    # 可能指向只有 event_log 表的库 (retention 测试), FK ON 会因
    # students 表不存在而写失败。各层保持既有 FK 语义。
    conn.execute("PRAGMA journal_mode = WAL")
    return backend, conn
