"""12.5 (0-D): PostgreSQL schema — 9 张主表 (镜像 SQLite SCHEMA_SQL).

与 SQLite 版 (db.py SCHEMA_SQL) 的差异映射:
  - TEXT PRIMARY KEY / UNIQUE / FK / INDEX     → 同名同义 (语法一致)
  - INTEGER PRIMARY KEY AUTOINCREMENT          → BIGINT GENERATED BY DEFAULT AS IDENTITY
  - REAL                                       → DOUBLE PRECISION
  - BLOB (trajectory_snapshots 的 *_snapshot)  → BYTEA
  - JSON TEXT 列                               → **保持 TEXT** (评估结论见下)

JSONB 评估结论 (12.5 第 1 项, 2026-09-12):
  **Phase 0 不采用 JSONB, 维持 TEXT**。理由:
  1. 全仓检索确认: 9 张表的 JSON 列当前全部是"整存整取" (写 json.dumps
     字符串, 读 json.loads), 没有任何 SQL 级 JSON 查询/索引需求
  2. 5 个持久化写入口 (db.py / dual_agent_store / lca_store / event_log /
     evidence_engine) 统一传 JSON 字符串 — JSONB 列会因 text→jsonb 无隐式
     赋值转换而全部写失败, 需要改造全部写入口的参数封装, 迁移风险面 ×5
  3. 上层消费者 (teacher._json_field / belief._get_or_create_student 恢复
     路径等) 都对返回值做 json.loads — JSONB 会返回 dict, 形状不一致会
     引入跨后端行为分叉
  升级路径 (将来真有 SQL 级 JSON 查询需求时, 一次性无损转换):
    ALTER TABLE students ALTER COLUMN current_state_5d TYPE jsonb
        USING current_state_5d::jsonb;
    (同时改造写入口传 psycopg Jsonb 包装 + 读路径接 dict 形状, 见
     cogedu/persistence/adapter.py normalize_value 已预留)

类型注记:
  - 布尔语义列 (judged / causal_significant / is_degraded_mode /
    human_review_requested / fallback_to_single_agent / structured_correctness)
    维持 INTEGER (0/1): 代码写入口已统一传 int, 读路径断言 0/1 —
    BOOLEAN 会让 psycopg 返回 True/False, 引入跨后端分叉, 不值得
  - TEXT NOT NULL 的时间戳列维持 TEXT (ISO 字符串): 与 SQLite 行为一致,
    排序语义在 ISO 格式下等价, 不引入 timestamptz 的时区语义变化
"""

# 9 张表一次建齐 (PG 全新库无历史包袱, 不需要 SQLite 版的
# CASCADE 重建/ALTER 增列迁移逻辑 — init_schema 对 PG 直接执行本脚本)
PG_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS students (
    student_id TEXT PRIMARY KEY,
    grade_level INTEGER,
    subject TEXT DEFAULT 'math',
    created_at TEXT NOT NULL,
    last_active_at TEXT,

    current_state_5d TEXT,
    current_bloom_profile TEXT,
    current_learning_dna TEXT,
    tc_states TEXT,
    misconception_history TEXT,
    trajectory_summary TEXT,

    confidence DOUBLE PRECISION DEFAULT 0.5,
    version TEXT DEFAULT 'v1.0',
    consent_version INTEGER DEFAULT 0,
    anonymized_id TEXT,
    warmup_count INTEGER DEFAULT 0,
    probe_due_in INTEGER DEFAULT 8,
    probe_count INTEGER DEFAULT 0,
    response_history TEXT,
    theta_cov TEXT,
    cognitive_twin TEXT,

    UNIQUE(anonymized_id)
);

CREATE INDEX IF NOT EXISTS idx_students_grade ON students(grade_level);
CREATE INDEX IF NOT EXISTS idx_students_last_active ON students(last_active_at);

CREATE TABLE IF NOT EXISTS interventions (
    intervention_id TEXT PRIMARY KEY,
    student_id TEXT NOT NULL,
    timestamp TEXT NOT NULL,

    intervention_type TEXT NOT NULL,
    bloom_target TEXT NOT NULL,
    target_skills TEXT,
    target_misconceptions TEXT,
    target_tcs TEXT,
    difficulty DOUBLE PRECISION,
    quantity INTEGER,
    feedback_density DOUBLE PRECISION,
    scaffolding_level DOUBLE PRECISION,
    clt_level INTEGER,
    ca_stage INTEGER,
    bjork_triggers TEXT,
    expected_gain DOUBLE PRECISION,
    expected_risk DOUBLE PRECISION,
    rationale_text TEXT,
    actual_state_delta DOUBLE PRECISION,
    actual_bloom_delta TEXT,
    causal_effect DOUBLE PRECISION,
    causal_p_value DOUBLE PRECISION,
    causal_significant INTEGER DEFAULT 0,
    calibration_round INTEGER DEFAULT 0,
    is_degraded_mode INTEGER DEFAULT 0,
    human_review_requested INTEGER DEFAULT 0,

    FOREIGN KEY (student_id) REFERENCES students(student_id)
);

CREATE INDEX IF NOT EXISTS idx_interventions_student ON interventions(student_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_interventions_bloom ON interventions(bloom_target);

CREATE TABLE IF NOT EXISTS calibration_log (
    calibration_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    calibration_round INTEGER NOT NULL,

    message_type TEXT NOT NULL,
    message_payload TEXT,
    state_before TEXT,
    state_after TEXT,
    trigger_reason TEXT,
    trigger_evidence TEXT,
    interaction_mode TEXT,
    outcome TEXT,
    human_review_requested INTEGER DEFAULT 0,
    fallback_to_single_agent INTEGER DEFAULT 0,
    duration_ms INTEGER,

    FOREIGN KEY (student_id) REFERENCES students(student_id)
);

CREATE INDEX IF NOT EXISTS idx_calibration_student ON calibration_log(student_id, timestamp);

CREATE TABLE IF NOT EXISTS bloom_goals (
    goal_id TEXT PRIMARY KEY,
    subject TEXT NOT NULL,
    skill_id TEXT NOT NULL,
    skill_name TEXT,
    bloom_layer INTEGER NOT NULL,
    description TEXT,
    cognitive_objectives TEXT,
    assessment_criteria TEXT,
    threshold_concepts TEXT,
    misconceptions TEXT,
    prerequisites TEXT,
    follow_ups TEXT,
    curriculum_standard_ref TEXT,
    created_by TEXT,
    created_at TEXT,
    version TEXT DEFAULT 'v1.0',

    UNIQUE(subject, skill_id, bloom_layer)
);

CREATE INDEX IF NOT EXISTS idx_bloom_goals_subject ON bloom_goals(subject, bloom_layer);
CREATE INDEX IF NOT EXISTS idx_bloom_goals_skill ON bloom_goals(skill_id);

CREATE TABLE IF NOT EXISTS trajectory_snapshots (
    snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    snapshot_type TEXT,
    epoch INTEGER,
    state_snapshot BYTEA,
    bloom_profile_snapshot BYTEA,
    learning_dna_snapshot BYTEA,
    grade_level INTEGER,
    semester TEXT,
    transfer_metadata TEXT,

    FOREIGN KEY (student_id) REFERENCES students(student_id)
);

CREATE INDEX IF NOT EXISTS idx_trajectory_student ON trajectory_snapshots(student_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_trajectory_type ON trajectory_snapshots(snapshot_type);

CREATE TABLE IF NOT EXISTS event_log (
    event_id TEXT PRIMARY KEY,
    student_id TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    source TEXT NOT NULL,
    event_type TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_event_log_student ON event_log(student_id, timestamp);

CREATE TABLE IF NOT EXISTS evidence_log (
    evidence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id TEXT NOT NULL,
    problem_id TEXT,
    timestamp TEXT NOT NULL,

    raw_response TEXT,
    raw_response_time DOUBLE PRECISION,
    raw_explanation TEXT,
    raw_reflection TEXT,
    llm_critic_input TEXT,
    llm_critic_output TEXT,
    llm_critic_temperature DOUBLE PRECISION,
    llm_critic_tokens INTEGER,
    structured_correctness INTEGER,
    structured_explanation_quality DOUBLE PRECISION,
    structured_confusion_signals TEXT,
    structured_self_evaluation DOUBLE PRECISION,
    state_before_update TEXT,
    state_after_update TEXT,
    state_delta DOUBLE PRECISION,
    misc_hits TEXT,
    tc_signals TEXT,
    quality_score DOUBLE PRECISION,

    FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_evidence_student ON evidence_log(student_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_evidence_problem ON evidence_log(problem_id);

CREATE TABLE IF NOT EXISTS misconception_evidence (
    student_id TEXT NOT NULL,
    misc_id TEXT NOT NULL,
    success_count INTEGER NOT NULL DEFAULT 0,
    failure_count INTEGER NOT NULL DEFAULT 0,
    last_updated TEXT NOT NULL,
    PRIMARY KEY (student_id, misc_id),
    FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_misconception_evidence_student
    ON misconception_evidence(student_id);

CREATE TABLE IF NOT EXISTS judge_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id TEXT,
    problem_id TEXT,
    provider TEXT,
    model TEXT,
    attempts INTEGER,
    latency_ms DOUBLE PRECISION,
    judged INTEGER NOT NULL DEFAULT 0,
    error_code TEXT,
    raw_output TEXT,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_judge_audit_student
    ON judge_audit_log(student_id, created_at);
"""

# students 表建表即含增量列 (warmup_count 等) — SQLite 版靠 ALTER 迁移补的
# 列在 PG DDL 里直接内联, 见上方 students 定义
